import type { Metadata } from "next";
import { Prompt } from "next/font/google";
import "./globals.css";

export const metadata: Metadata = {
  title: "THXNXKXT - FLOW LIFE",
  description: "Generated by create next app",
};

const prompt = Prompt({
  subsets: ["latin", "thai"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-prompt",
  display: "swap",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${prompt.variable}`} suppressHydrationWarning={true}>
      <body className="font-sans antialiased">{children}</body>
    </html>
  );
}